---
- name: Execute task for Ubuntu servers
  include_tasks: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Execute task for CentOS servers
  include_tasks: centos.yml
  when: ansible_distribution == "CentOS"

- name: Execute task for RedHat servers
  include_tasks: redhat.yml
  when: ansible_distribution == "RedHat"

- name: Execute task for OracleLinux servers
  include_tasks: redhat.yml
  when: ansible_distribution == "OracleLinux"
...
